crt0.o              :   crt0.s \
                        apple2.inc iocs.inc
iocs.o              :   iocs.s iocs.inc \
                        apple2.inc
app.o               :   app.s app.inc \
                        apple2.inc iocs.inc
